### ISSUE TITLE
HEC_Box Bug

### ISSUE THREAD

**Issue by AmnonOwed** [wblut/HE_Mesh2014#22]
I've been working on an updated version of HemeshGui (which will be much better than the previous one hopefully) using Hemesh version 2.0.11 Persephone. Making a lot of progress, but also running into two issues, for which I will open separate issues.

Something strange is going on with HEC_Box's **setWidthSegments** method. When it's value is larger than the value of setDepthSegments, it results in an ArrayOutOfBoundsException. Also, when you use setHeightSegments or setDepthSegments, the segmentation for two sides is set. I'm not entirely sure if the latter is a bug or a feature. But I suppose the AOB is definitely a bug.

Below a code example that reproduces the bug:

```java
import wblut.math.*;
import wblut.processing.*;
import wblut.core.*;
import wblut.hemesh.*;
import wblut.geom.*;

HE_Mesh mesh;
WB_Render render;

void setup() {
  size(800, 800, P3D);
  smooth(8); 
  HEC_Box creator=new HEC_Box();
  creator.setWidth(100).setHeight(200).setDepth(300); 
  creator.setWidthSegments(2).setHeightSegments(1).setDepthSegments(1); // (setWidthSegments > setDepthSegments) == NullPointerException
  mesh = new HE_Mesh(creator); 
  HET_Diagnosis.validate(mesh);
  render = new WB_Render(this);
}

void draw() {
  background(255);
  directionalLight(255, 255, 255, 1, 1, -1);
  directionalLight(127, 127, 127, -1, -1, 1);
  translate(400, 400, 100);
  rotateY(mouseX*1.0f/width*TWO_PI);
  rotateX(mouseY*1.0f/height*TWO_PI);
  stroke(0);
  render.drawEdges(mesh);
  noStroke();
  render.drawFaces(mesh);
}
```

**Comment by wblut** [comment]
* There was an error in the calculation of the vertex texture coordinates. A wrong constant was reused for the different directions. This is now fixed in the repository.
* The segment parameters determine the number of divisions along the three axes. Each parameter consequentially affects two sets of sides, the sides parallel to that direction. For example, setting number of segments along the height, Z-axis, will divide X- and Y-faces.

**Comment by AmnonOwed** [comment]
Ah, that makes sense. Thanks for the quick response! :+1:
